# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookName', models.CharField(max_length=30)),
                ('length', models.IntegerField(default=30)),
                ('description', models.TextField(max_length=200)),
                ('isbn', models.CharField(max_length=30)),
                ('state', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='borrowBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowDate', models.DateField(auto_now_add=True)),
                ('actualBackDate', models.DateField(blank=True)),
                ('currentBook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piaoliu.book')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=30)),
                ('banji', models.CharField(max_length=30)),
                ('xuehao', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('phoneNumber', models.IntegerField()),
                ('email', models.EmailField(max_length=30)),
                ('wechat', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='borrowbook',
            name='currentUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piaoliu.user'),
        ),
    ]
