# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 13:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=30)),
                ('state', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='BorrowBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowDate', models.DateField(auto_now_add=True)),
                ('actualBackDate', models.DateField(blank=True, null=True)),
                ('currentBook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piaoliu.Book')),
            ],
        ),
        migrations.CreateModel(
            name='douban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookName', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('isbn', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=30)),
                ('rating', models.FloatField()),
                ('length', models.IntegerField(blank=True, default=30, null=True)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='orderBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDate', models.DateField(auto_now_add=True)),
                ('state', models.IntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piaoliu.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(blank=True, max_length=30, null=True)),
                ('banji', models.CharField(max_length=30)),
                ('xuehao', models.CharField(max_length=30)),
                ('phoneNumber', models.CharField(max_length=30)),
                ('wechat', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='orderbook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piaoliu.Student'),
        ),
        migrations.AddField(
            model_name='borrowbook',
            name='currentUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piaoliu.Student'),
        ),
        migrations.AddField(
            model_name='book',
            name='doubanxinxi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piaoliu.douban'),
        ),
    ]
