# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piaoliu', '0002_auto_20170328_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='doubanxinxi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='piaoliu.douban'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=30),
        ),
    ]
