# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piaoliu', '0011_auto_20170321_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='length',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='borrowbook',
            name='currentBook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piaoliu.Book'),
        ),
        migrations.AlterField(
            model_name='borrowbook',
            name='currentUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piaoliu.User'),
        ),
    ]
