# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piaoliu', '0012_auto_20170321_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='douban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=30)),
                ('subjectId', models.CharField(max_length=30)),
                ('recommendBook', models.TextField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='borrowbook',
            name='currentBook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piaoliu.Book'),
        ),
        migrations.AlterField(
            model_name='borrowbook',
            name='currentUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piaoliu.User'),
        ),
    ]
